// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { AuthorConfig } from "./types";

export const author: AuthorConfig = {
  name: "Jonathan Borchardt",
  tagline: "Always shippable, always improving",
  links: {
    github: "https://github.com/jonborchardt",
    linkedin: "https://www.linkedin.com/in/borchardt/",
  },
};
