// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { SeriesRegistry } from "./types";

export const series = {
  "agent-built": {
    title: "Agent-Built",
    description:
      "How a coding agent built this site in an afternoon — and the contracts, authoring primitives, and repo-as-expert system that let it keep publishing.",
  },
  finances: {
    title: "Finances",
    description:
      "Replaying one retirement plan across every start year since 1928: the simulator, the agent pipeline behind it, and 98 lives ending broke or on $5.8 million.",
  },
  worldlock: {
    title: "WorldLock",
    description:
      "A native Android AR app pinning city towers, the Earth and the live ISS to where they actually are — built by an agent-driven workflow, no IDE and no cable.",
  },
  "sierra-games": {
    title: "Sierra Games",
    description:
      "Upscaling Sierra's SCI0 vector backgrounds 6× without breaking them: flood fills that leak, a native-resolution render as the oracle, an anchor-graph rewrite.",
  },
} as const satisfies SeriesRegistry;

export type SeriesId = keyof typeof series;
export const SERIES_IDS = Object.keys(series) as [SeriesId, ...SeriesId[]];
