// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { SeriesRegistry } from "./types";

export const series = {
  finances: {
    title: "Finances",
    description:
      "Notes on personal finance: the models, the numbers, and the tools built to track them.",
  },
  worldlock: {
    title: "WorldLock",
    description:
      "Building WorldLock in the open: the design decisions, the tooling, and what shipped along the way.",
  },
  "sierra-games": {
    title: "Sierra Games",
    description:
      "Revisiting the Sierra adventure games: their design, their engines, and what still holds up.",
  },
} as const satisfies SeriesRegistry;

export type SeriesId = keyof typeof series;
export const SERIES_IDS = Object.keys(series) as [SeriesId, ...SeriesId[]];
