// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { SiteConfig } from "./types";

export const site: SiteConfig = {
  name: "Always Shippable",
  description:
    "Thoughts on building always shippable systems, moving fast without breaking things, and making complex work simple and enjoyable.",
  disclaimer: "Views are my own and do not represent my employer.",
  url: "https://jonborchardt.github.io",
  locale: "en",
  featuredPost: null,
  nav: [
    { label: "All Posts", href: "/all-posts/" },
    { label: "Series", href: "/series/" },
    { label: "About", href: "/about/" },
  ],
};
