// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { SiteConfig } from "./types";

export const site: SiteConfig = {
  name: "Always Shippable",
  description:
    "Thoughts on engineering systems, product design, AI tooling, and keeping things always shippable.",
  url: "https://jonborchardt.github.io",
  locale: "en",
  featuredPost: null,
  nav: [
    { label: "Archive", href: "/archive/" },
    { label: "Series", href: "/series/" },
    { label: "About", href: "/about/" },
  ],
};
