// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { TagRegistry } from "./types";

export const tags = {
  engineering: { label: "Engineering" },
  "ai-tooling": { label: "AI Tooling" },
  "product-design": { label: "Product Design" },
  meta: { label: "Meta" },
} as const satisfies TagRegistry;

export type TagId = keyof typeof tags;
export const TAG_IDS = Object.keys(tags) as [TagId, ...TagId[]];
