// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.
import type { TagRegistry } from "./types";

export const tags = {
  engineering: { label: "Engineering" },
  "ai-assisted-coding": { label: "AI-Assisted Coding" },
  "developer-tools": { label: "Developer Tools" },
  "code-quality": { label: "Code Quality" },
  typescript: { label: "TypeScript" },
  kotlin: { label: "Kotlin" },
  react: { label: "React" },
  astro: { label: "Astro" },
  mdx: { label: "MDX" },
  "web-development": { label: "Web Development" },
  "web-performance": { label: "Web Performance" },
  "design-system": { label: "Design System" },
  accessibility: { label: "Accessibility" },
  android: { label: "Android" },
  "augmented-reality": { label: "Augmented Reality" },
  geospatial: { label: "Geospatial" },
  graphics: { label: "Graphics" },
  gamedev: { label: "Game Dev" },
  retrocomputing: { label: "Retrocomputing" },
  llm: { label: "LLM" },
  nlp: { label: "NLP" },
  "knowledge-graph": { label: "Knowledge Graph" },
  "data-viz": { label: "Data Viz" },
  simulation: { label: "Simulation" },
  "personal-finance": { label: "Personal Finance" },
  investing: { label: "Investing" },
} as const satisfies TagRegistry;

export type TagId = keyof typeof tags;
export const TAG_IDS = Object.keys(tags) as [TagId, ...TagId[]];
