/**
 * Node-only writer for src/config/*.ts. Produces the exact file text from a per-file template
 * (so the admin can round-trip TS config without losing the `as const` key inference that
 * SERIES_IDS / TAG_IDS / z.enum depend on), formats it with Prettier, and writes it.
 * Never imported by production pages.
 */
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import * as prettier from "prettier";
import { configSchemas, type ConfigName } from "../config/types.ts";

const HEADER =
  "// Generated by the dev admin (src/dev/config-writer.ts). Edit values, not structure.";

const TEMPLATES: Record<ConfigName, (json: string) => string> = {
  site: (json) => `${HEADER}
import type { SiteConfig } from "./types";

export const site: SiteConfig = ${json};
`,
  author: (json) => `${HEADER}
import type { AuthorConfig } from "./types";

export const author: AuthorConfig = ${json};
`,
  series: (json) => `${HEADER}
import type { SeriesRegistry } from "./types";

export const series = ${json} as const satisfies SeriesRegistry;

export type SeriesId = keyof typeof series;
export const SERIES_IDS = Object.keys(series) as [SeriesId, ...SeriesId[]];
`,
  tags: (json) => `${HEADER}
import type { TagRegistry } from "./types";

export const tags = ${json} as const satisfies TagRegistry;

export type TagId = keyof typeof tags;
export const TAG_IDS = Object.keys(tags) as [TagId, ...TagId[]];
`,
};

export const configPath = (name: ConfigName, root = process.cwd()) =>
  resolve(root, "src/config", `${name}.ts`);

/** Validate + render the file text (Prettier-formatted). Throws a Zod error on invalid data. */
export async function serializeConfig(name: ConfigName, data: unknown): Promise<string> {
  const parsed = configSchemas[name].parse(data);
  const text = TEMPLATES[name](JSON.stringify(parsed));
  const filepath = configPath(name);
  const options = (await prettier.resolveConfig(filepath)) ?? {};
  return prettier.format(text, { ...options, filepath });
}

export async function writeConfig(name: ConfigName, data: unknown): Promise<string> {
  const text = await serializeConfig(name, data);
  await writeFile(configPath(name), text, "utf8");
  return text;
}
